export function Footer() {
  return (
    <footer className="border-t border-[var(--border-color)] bg-[var(--navy-primary)] px-4 py-8">
      <div className="mx-auto max-w-4xl text-center">
        <p className="text-xs text-[var(--text-tertiary)]">
          Generated by Superagent.
        </p>
      </div>
    </footer>
  )
}
